using System.ComponentModel;

namespace BilliardIQ.Mobile.Services;

public  sealed partial class LocalizationManager : INotifyPropertyChanged
{
    public static readonly LocalizationManager Instance = new();

    private string _language = Preferences.Default.Get("app_language", "en");

    private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["en"] = new()
        {
            ["Auth_Title"] = "Sign in to your account",
            ["Auth_Email"] = "Email",
            ["Auth_Password"] = "Password",
            ["Auth_SignIn"] = "Sign in",
            ["Auth_HaveInvite"] = "I have an invite code",
            ["Auth_Required"] = "Fill in all fields.",
            ["Auth_InvalidCredentials"] = "Email or password is incorrect.",
            ["Auth_Forbidden"] = "You do not have permission for this.",
            ["Auth_ServerError"] = "The server returned an error. Try again.",
            ["Auth_NetworkError"] = "Cannot reach the server. Check your connection.",
            ["Forgot_Link"] = "Forgot password?",
            ["Forgot_Title"] = "Reset password",
            ["Forgot_Hint"] = "Enter your email. We will send you a 6 digit code.",
            ["Forgot_SendCode"] = "Send code",
            ["Forgot_Code"] = "6 digit code",
            ["Forgot_CodeSent"] = "If the email is registered, a code has been sent. It is valid for 15 minutes.",
            ["Forgot_Submit"] = "Set new password",
            ["Forgot_Done"] = "Password changed. You can sign in now.",
            ["Forgot_Back"] = "Back to sign in",
            ["Register_Title"] = "Join with invite code",
            ["Register_Hint"] = "Enter the invite code your club manager gave you and choose your email and password.",
            ["Register_Code"] = "Invite code",
            ["Register_Submit"] = "Create account",
            ["Pwd_Title"] = "Change password",
            ["Pwd_Forced"] = "You must change your temporary password before continuing.",
            ["Pwd_Current"] = "Current password",
            ["Pwd_New"] = "New password",
            ["Pwd_Confirm"] = "Repeat password",
            ["Pwd_Submit"] = "Change password",
            ["Pwd_TooShort"] = "The password must be at least 6 characters.",
            ["Pwd_Mismatch"] = "The passwords do not match.",
            ["Org_Title"] = "Choose organization",
            ["Org_Subtitle"] = "Which organization do you want to open?",
            ["Account_Title"] = "Account",
            ["Account_ChangeOrganization"] = "Change organization",
            ["Account_ChangePassword"] = "Change password",
            ["Account_ChangeEmail"] = "Change email",
            ["Account_NewEmail"] = "New email",
            ["Account_EmailChanged"] = "Email updated.",
            ["Account_SignOut"] = "Sign out",
            ["Account_Save"] = "Save",
            ["Account_Saved"] = "Saved.",
            ["Account_TakePhoto"] = "Take photo",
            ["Account_ChoosePhoto"] = "Choose photo",
            ["Account_ChooseAvatar"] = "Choose avatar",
            ["Account_RemovePhoto"] = "Remove photo",
            ["Account_PhotoFailed"] = "The photo could not be read.",
            ["Account_Name"] = "Name",
            ["Account_Nickname"] = "Nickname",
            ["Account_DisplayName"] = "Name",
            ["Account_Level"] = "Level",
            ["Account_LevelBeginner"] = "Beginner",
            ["Account_LevelIntermediate"] = "Intermediate",
            ["Account_LevelAdvanced"] = "Advanced",
            ["Account_LevelProfessional"] = "Professional",
            ["Account_LicenseNo"] = "License number",
            ["Account_LicenseValidUntil"] = "License valid until",
            ["Account_BirthDate"] = "Birth date",
            ["Account_Gender"] = "Gender",
            ["Account_GenderMale"] = "Male",
            ["Account_GenderFemale"] = "Female",
            ["Account_GenderOther"] = "Other",
            ["Account_GenderUndisclosed"] = "Prefer not to say",
            ["Account_Handedness"] = "Playing hand",
            ["Account_HandRight"] = "Right",
            ["Account_HandLeft"] = "Left",
            ["Account_ShortcutNumber"] = "Shortcut number",
            ["Account_Association"] = "Association",
            ["Account_Country"] = "Country",
            ["Account_Region"] = "Region",
            ["Account_City"] = "City",
            ["Account_Clubs"] = "Clubs",
            ["Account_Teams"] = "Teams",
            ["Account_Phone"] = "Phone",
            ["Account_Language"] = "Language",
            ["Account_DateInvalid"] = "Dates must look like 2027-06-30.",
            ["PlayerHome_Title"] = "My stats",
            ["PlayerHome_LastMatches"] = "Last 5 matches",
            ["PlayerHome_NoMatches"] = "No matches yet.",
            // Stats card
            ["Stats_Matches"]   = "Matches",
            ["Stats_Average"]   = "Average",
            ["Stats_HighRun"]   = "High Run",
            ["Stats_LastMatch"] = "Last Match",
            ["Result_Win"]      = "Win",
            ["Result_Loss"]     = "Loss",
            ["Result_Draw"]     = "Draw",
            ["Result_NoGame"]   = "-",
            ["Serie"]           = "Serie",

            // Game list
            ["GameList_Delete"] = "Delete",

            // New game
            ["NewGame_SyncRejected"]     = "The server did not accept this match",
            ["NewGame_DeleteFailed"]     = "The match could not be deleted from the server",
            ["NewGame_Title"]            = "Add New Game",
            ["NewGame_UpdateTitle"]      = "Update Game",
            ["NewGame_OpponentName"]     = "Enter Opponent Name",
            ["NewGame_Location"]         = "Enter Location",
            ["NewGame_Score"]            = "Score",
            ["NewGame_MyScore"]          = "My Score",
            ["NewGame_OpponentScore"]    = "Opponent Score",
            ["NewGame_HighestRun"]       = "Highest Run",
            ["NewGame_Innings"]          = "Innings",
            ["Stats_BestAverage"]        = "Best Avg",
            ["NewGame_SelectBall"]       = "Select Ball",
            ["NewGame_Notes"]            = "Notes (optional)",
            ["NewGame_NotesPlaceholder"] = "Add a description or notes...",
            ["NewGame_ScoreboardPhoto"]  = "Scoreboard Photo",
            ["NewGame_Remove"]           = "Remove",

            // Common actions
            ["Action_Save"]   = "Save",
            ["Action_Update"] = "Update",
            ["Action_Ok"]     = "OK",
            ["Action_Cancel"] = "Cancel",

            // Profile
            ["Search_Placeholder"]   = "Search...",
            ["Search_NoResults"]     = "No results found",
            ["Action_Cancel"]        = "Cancel",
            ["Ocr_DetectedTitle"]    = "Scores Detected",
            ["Ocr_DetectedMsg"]      = "Found {0} – {1}. Apply to score fields?",
            ["Ocr_Yes"]              = "Apply",
            ["Ocr_No"]               = "Skip",
            ["Ocr_Failed"]           = "Could not read scores from photo",
            ["Ocr_Reading"]          = "Reading scoreboard...",

            // New game — profile guard

            // Game (Play) page
            ["Game_Title"]       = "3-Cushion Billiards",
            ["Game_Description"] = "Tap PLAY to start a 2-player 3-cushion match.",
            ["Game_Play"]        = "PLAY",
            ["Game_Player1"]     = "Player 1",
            ["Game_Player2"]     = "Player 2",

            // Platform not supported
            ["Platform_DoesNotSupport"]         = "Platform Not Supported",
            ["Platform_DoesNotSupport_Message"] = "The 3-cushion game only works on Android.",
            ["Platform_DoesNotSupport_Ok"]      = "OK",

            // Table vision / ball detection
            ["TV_White"]        = "white ball",
            ["TV_Yellow"]       = "yellow ball",
            ["TV_Red"]          = "red ball",
            ["TV_Corners"]      = "4 corners",
            ["TV_TopLeft"]      = "Top-Left",
            ["TV_TopRight"]     = "Top-Right",
            ["TV_BottomRight"]  = "Bottom-Right",
            ["TV_BottomLeft"]   = "Bottom-Left",
            ["TV_NotFound"]     = "No balls or table detected — try better lighting and a more direct angle.",
            ["TV_ReadError"]    = "Could not read image.",
            ["TV_Analyzing"]    = "Analyzing...",
            ["TV_Reanalyze"]    = "🔄 Re-analyze",
            ["TV_Analyze"]      = "🔍 Analyze",
            ["TV_Analyzing2"]   = "⏳ Analyzing...",

            // Raspberry Pi connection
            ["Connect_Title"]             = "Connect to Table",
            ["Connect_WebSocketUrl"]      = "WebSocket URL",
            ["Connect_Connect"]           = "Connect",
            ["Connect_Disconnect"]        = "Disconnect",
            ["Connect_Cancel"]            = "Cancel",
            ["Connect_Timeout"]           = "Connection timed out. Make sure the Pi is powered on, reachable on the network, and the URL is correct.",
            ["Connect_StatusConnected"]   = "Connected via {0}",
            ["Connect_StatusConnecting"]  = "Connecting...",
            ["Connect_StatusFailed"]      = "Connection failed: {0}",
            ["Connect_StatusDisconnected"]= "Not connected",

            // Scoreboard Players
            ["AddPlayer_Title"]       = "Add Player",
            ["AddPlayer_UpdateTitle"] = "Update Player",
            ["AddPlayer_NickName"]    = "Nickname",
            ["AddPlayer_Name"]        = "Name",
            ["AddPlayer_Avatar"]      = "Avatar",
            ["AddPlayer_Team"]        = "Team (optional)",
            ["AddPlayer_ShortcutNumber"] = "Shortcut #",
            ["AddPlayer_ShortcutNumberInvalid"] = "Enter a whole number greater than 0.",
            ["AddPlayer_ShortcutNumberTaken"] = "That shortcut number is already used by {0}.",

            // Scoreboard
            ["Scoreboard_Title"]       = "Scoreboard",
            ["Scoreboard_Reset"]       = "Reset Scores",
            ["Scoreboard_Enter"]       = "Enter",
            ["Scoreboard_MatchTarget"] = "Target",
            ["Scoreboard_StartNewGame"]= "Start New Game",
            ["Scoreboard_EndGame"]     = "End Game",
            ["Scoreboard_WarmUp"]      = "Warm Up",
            ["Scoreboard_WarmUpTitle"] = "Warm-up duration",
            ["Scoreboard_MinutesFormat"] = "{0} min",
            ["Scoreboard_Reconnect"]   = "Reconnect",
            ["Scoreboard_PickPlayer"] = "Select Player",
            ["Scoreboard_NoPlayers"]  = "No players yet. Add one first.",
            ["Rank_Title"]              = "Ranking",
            ["Rank_Players"]            = "Players",
            ["Rank_Period"]             = "Period",
            ["Rank_Period30"]           = "Last 30 days",
            ["Rank_Period90"]           = "Last 90 days",
            ["Rank_Period6m"]           = "Last 6 months",
            ["Rank_PeriodYear"]         = "This year",
            ["Rank_PeriodAll"]          = "All time",
            ["Rank_Sort"]               = "Sort by",
            ["Rank_SortAverage"]        = "Average",
            ["Rank_SortWins"]           = "Wins",
            ["Rank_SortHighRun"]        = "High run",
            ["Rank_SortMatches"]        = "Matches",
            ["Rank_SortWinPercent"]     = "Win %",
            ["Rank_Empty"]              = "No matches in this period.",
            ["Manage_EditPlayer"]       = "Edit player",
            ["Manage_FirstName"]        = "First name",
            ["Manage_LastName"]         = "Last name",
            ["Manage_Title"]            = "Management",
            ["Manage_Tables"]           = "Tables",
            ["Manage_Players"]          = "Players",
            ["Manage_Teams"]            = "Teams",
            ["Manage_Empty"]            = "Nothing to show.",
            ["Manage_Table"]            = "Table",
            ["Manage_ScoreboardNo"]     = "Scoreboard",
            ["Manage_NoScoreboard"]     = "No scoreboard assigned",
            ["Manage_Available"]        = "Available",
            ["Manage_InUse"]            = "In use",
            ["Manage_Reserved"]         = "Reserved",
            ["Manage_Maintenance"]      = "Maintenance",
            ["Manage_OutOfService"]     = "Out of service",
            ["Admin_Teams"]             = "Teams",
            ["Admin_TeamName"]          = "Team name",
            ["Admin_AddTeam"]           = "Add Team",
            ["Admin_TeamsEmpty"]        = "No teams yet. Add one above.",
            ["Admin_Players"]           = "Players",
            ["Admin_AddPlayer"]         = "Add Player",
            ["Admin_PlayersEmpty"]      = "No players yet. Add one above.",
            ["Admin_DeletePlayer"]        = "Delete Player",
            ["Admin_DeletePlayerConfirm"] = "Permanently delete {0}? This cannot be undone.",
            ["Admin_DefaultPlayerDeleteBlocked"] = "This is a default player used by the Scoreboard page and can't be deleted.",
            ["Admin_DeleteTeam"]          = "Delete Team",
            ["Admin_DeleteTeamConfirm"]   = "Permanently delete {0}? This cannot be undone.",

            // Player match stats
            ["PlayerStats_Title"]         = "Player Stats",
            ["PlayerStats_Empty"]         = "No match results yet.",
            ["PlayerStats_Wins"]          = "Wins",
            ["PlayerStats_Losses"]        = "Losses",
            ["PlayerStats_AvgInnings"]    = "Avg Innings",
            ["PlayerStats_InningsChart"]  = "Innings per Match",
            ["PlayerStats_ScoringPace"]   = "Scoring Pace (Last Match)",
            ["PlayerStats_Started"]       = "Started: {0:g}",
            ["PlayerStats_Ended"]         = "Ended: {0:g}",

            // SSH console
            ["Ssh_Title"]           = "SSH Console",
            ["Ssh_Host"]            = "Host",
            ["Ssh_Port"]            = "Port",
            ["Ssh_Username"]        = "Username",
            ["Ssh_Password"]        = "Password",
            ["Ssh_SaveCredentials"] = "Save Credentials",
            ["Ssh_Command"]         = "Command",
            ["Ssh_Run"]             = "Run",
            ["Ssh_Output"]          = "Output",
            ["PlayerStats_MatchHistory"]  = "Match History",
            ["PlayerStats_Opponent"]      = "Opponent",
            ["PlayerStats_Win"]           = "W",
            ["PlayerStats_Loss"]          = "L",
        },
        ["tr"] = new()
        {
            ["Auth_Title"] = "Hesabınıza giriş yapın",
            ["Auth_Email"] = "E-posta",
            ["Auth_Password"] = "Parola",
            ["Auth_SignIn"] = "Giriş yap",
            ["Auth_HaveInvite"] = "Davet kodum var",
            ["Auth_Required"] = "Tüm alanları doldurun.",
            ["Auth_InvalidCredentials"] = "E-posta veya parola yanlış.",
            ["Auth_Forbidden"] = "Bunun için yetkiniz yok.",
            ["Auth_ServerError"] = "Sunucu hata verdi. Tekrar deneyin.",
            ["Auth_NetworkError"] = "Sunucuya ulaşılamıyor. Bağlantınızı kontrol edin.",
            ["Forgot_Link"] = "Parolamı unuttum",
            ["Forgot_Title"] = "Parolayı sıfırla",
            ["Forgot_Hint"] = "E-postanızı girin. 6 haneli bir kod göndereceğiz.",
            ["Forgot_SendCode"] = "Kod gönder",
            ["Forgot_Code"] = "6 haneli kod",
            ["Forgot_CodeSent"] = "E-posta kayıtlıysa kod gönderildi. 15 dakika geçerlidir.",
            ["Forgot_Submit"] = "Yeni parolayı kaydet",
            ["Forgot_Done"] = "Parola değişti. Şimdi giriş yapabilirsiniz.",
            ["Forgot_Back"] = "Girişe dön",
            ["Register_Title"] = "Davet koduyla katıl",
            ["Register_Hint"] = "Salon yöneticinizin verdiği davet kodunu girin, e-posta ve parolanızı belirleyin.",
            ["Register_Code"] = "Davet kodu",
            ["Register_Submit"] = "Hesap oluştur",
            ["Pwd_Title"] = "Parola değiştir",
            ["Pwd_Forced"] = "Devam etmeden önce geçici parolanızı değiştirmelisiniz.",
            ["Pwd_Current"] = "Mevcut parola",
            ["Pwd_New"] = "Yeni parola",
            ["Pwd_Confirm"] = "Parolayı tekrarlayın",
            ["Pwd_Submit"] = "Parolayı değiştir",
            ["Pwd_TooShort"] = "Parola en az 6 karakter olmalı.",
            ["Pwd_Mismatch"] = "Parolalar eşleşmiyor.",
            ["Org_Title"] = "Organizasyon seçin",
            ["Org_Subtitle"] = "Hangi organizasyonu açmak istiyorsunuz?",
            ["Account_Title"] = "Hesap",
            ["Account_ChangeOrganization"] = "Organizasyon değiştir",
            ["Account_ChangePassword"] = "Parola değiştir",
            ["Account_ChangeEmail"] = "E-posta değiştir",
            ["Account_NewEmail"] = "Yeni e-posta",
            ["Account_EmailChanged"] = "E-posta güncellendi.",
            ["Account_SignOut"] = "Çıkış yap",
            ["Account_Save"] = "Kaydet",
            ["Account_Saved"] = "Kaydedildi.",
            ["Account_TakePhoto"] = "Fotoğraf çek",
            ["Account_ChoosePhoto"] = "Fotoğraf seç",
            ["Account_ChooseAvatar"] = "Avatar seç",
            ["Account_RemovePhoto"] = "Fotoğrafı kaldır",
            ["Account_PhotoFailed"] = "Fotoğraf okunamadı.",
            ["Account_Name"] = "Ad",
            ["Account_Nickname"] = "Takma ad",
            ["Account_DisplayName"] = "Ad",
            ["Account_Level"] = "Seviye",
            ["Account_LevelBeginner"] = "Başlangıç",
            ["Account_LevelIntermediate"] = "Orta",
            ["Account_LevelAdvanced"] = "İleri",
            ["Account_LevelProfessional"] = "Profesyonel",
            ["Account_LicenseNo"] = "Lisans numarası",
            ["Account_LicenseValidUntil"] = "Lisans geçerlilik tarihi",
            ["Account_BirthDate"] = "Doğum tarihi",
            ["Account_Gender"] = "Cinsiyet",
            ["Account_GenderMale"] = "Erkek",
            ["Account_GenderFemale"] = "Kadın",
            ["Account_GenderOther"] = "Diğer",
            ["Account_GenderUndisclosed"] = "Belirtmek istemiyorum",
            ["Account_Handedness"] = "Oynadığı el",
            ["Account_HandRight"] = "Sağ",
            ["Account_HandLeft"] = "Sol",
            ["Account_ShortcutNumber"] = "Kısayol numarası",
            ["Account_Association"] = "Federasyon / temsilcilik",
            ["Account_Country"] = "Ülke",
            ["Account_Region"] = "Bölge",
            ["Account_City"] = "Şehir",
            ["Account_Clubs"] = "Kulüpler",
            ["Account_Teams"] = "Takımlar",
            ["Account_Phone"] = "Telefon",
            ["Account_Language"] = "Dil",
            ["Account_DateInvalid"] = "Tarih 2027-06-30 biçiminde olmalı.",
            ["PlayerHome_Title"] = "İstatistiklerim",
            ["PlayerHome_LastMatches"] = "Son 5 maç",
            ["PlayerHome_NoMatches"] = "Henüz maç yok.",
            ["Stats_Matches"]   = "Maçlar",
            ["Stats_Average"]   = "Ortalama",
            ["Stats_HighRun"]   = "En Yüksek",
            ["Stats_LastMatch"] = "Son Maç",
            ["Result_Win"]      = "Kazandı",
            ["Result_Loss"]     = "Kaybetti",
            ["Result_Draw"]     = "Berabere",
            ["Result_NoGame"]   = "-",
            ["Serie"]           = "Seri",

            ["GameList_Delete"] = "Sil",

            ["NewGame_SyncRejected"]     = "Sunucu bu maçı kabul etmedi",
            ["NewGame_DeleteFailed"]     = "Maç sunucudan silinemedi",
            ["NewGame_Title"]            = "Yeni Maç Ekle",
            ["NewGame_UpdateTitle"]      = "Maçı Güncelle",
            ["NewGame_OpponentName"]     = "Rakip Adı",
            ["NewGame_Location"]         = "Lokasyon",
            ["NewGame_Score"]            = "Skor",
            ["NewGame_MyScore"]          = "Benim Skorum",
            ["NewGame_OpponentScore"]    = "Rakip Skoru",
            ["NewGame_HighestRun"]       = "En Yüksek Seri",
            ["NewGame_Innings"]          = "El Sayısı",
            ["Stats_BestAverage"]        = "En İyi Ort.",
            ["NewGame_SelectBall"]       = "Top Seç",
            ["NewGame_Notes"]            = "Notlar (opsiyonel)",
            ["NewGame_NotesPlaceholder"] = "Açıklama veya not ekle...",
            ["NewGame_ScoreboardPhoto"]  = "Skorbord Fotoğrafı",
            ["NewGame_Remove"]           = "Kaldır",

            ["Action_Save"]   = "Kaydet",
            ["Action_Update"] = "Güncelle",
            ["Action_Ok"]     = "Tamam",
            ["Action_Cancel"] = "İptal",

            ["Search_Placeholder"]    = "Ara...",
            ["Search_NoResults"]      = "Sonuç bulunamadı",
            ["Action_Cancel"]         = "İptal",
            ["Ocr_DetectedTitle"]     = "Skor Algılandı",
            ["Ocr_DetectedMsg"]       = "{0} – {1} skoru bulundu. Skor alanlarına uygulansın mı?",
            ["Ocr_Yes"]               = "Uygula",
            ["Ocr_No"]                = "Atla",
            ["Ocr_Failed"]            = "Fotoğraftan skor okunamadı",
            ["Ocr_Reading"]           = "Skorbord okunuyor...",

            // New game — profile guard

            // Game (Play) page
            ["Game_Title"]       = "3-Bant Bilardo",
            ["Game_Description"] = "2 oyunculu 3-bant maçı başlatmak için OYNA'ya dokun.",
            ["Game_Play"]        = "OYNA",
            ["Game_Player1"]     = "Oyuncu 1",
            ["Game_Player2"]     = "Oyuncu 2",

            // Platform not supported
            ["Platform_DoesNotSupport"]         = "Platform Desteklenmiyor",
            ["Platform_DoesNotSupport_Message"] = "3-Bant oyunu yalnızca Android'de çalışır.",
            ["Platform_DoesNotSupport_Ok"]      = "Tamam",

            // Table vision / top tespiti
            ["TV_White"]        = "beyaz top",
            ["TV_Yellow"]       = "sarı top",
            ["TV_Red"]          = "kırmızı top",
            ["TV_Corners"]      = "4 köşe",
            ["TV_TopLeft"]      = "Sol-Üst",
            ["TV_TopRight"]     = "Sağ-Üst",
            ["TV_BottomRight"]  = "Sağ-Alt",
            ["TV_BottomLeft"]   = "Sol-Alt",
            ["TV_NotFound"]     = "Top veya masa algılanamadı — daha iyi aydınlatma ve dik açıyla tekrar deneyin.",
            ["TV_ReadError"]    = "Görüntü okunamadı.",
            ["TV_Analyzing"]    = "Analiz ediliyor...",
            ["TV_Reanalyze"]    = "🔄 Yeniden Analiz",
            ["TV_Analyze"]      = "🔍 Analiz Et",
            ["TV_Analyzing2"]   = "⏳ Analiz ediliyor...",

            // Raspberry Pi bağlantısı
            ["Connect_Title"]             = "Masaya Bağlan",
            ["Connect_WebSocketUrl"]      = "WebSocket Adresi",
            ["Connect_Connect"]           = "Bağlan",
            ["Connect_Disconnect"]        = "Bağlantıyı Kes",
            ["Connect_Cancel"]            = "İptal",
            ["Connect_Timeout"]           = "Bağlantı zaman aşımına uğradı. Pi'nin açık, ağda erişilebilir ve adresin doğru olduğundan emin olun.",
            ["Connect_StatusConnected"]   = "{0} ile bağlandı",
            ["Connect_StatusConnecting"]  = "Bağlanıyor...",
            ["Connect_StatusFailed"]      = "Bağlantı başarısız: {0}",
            ["Connect_StatusDisconnected"]= "Bağlı değil",

            // Skorbord Oyuncuları
            ["AddPlayer_Title"]       = "Oyuncu Ekle",
            ["AddPlayer_UpdateTitle"] = "Oyuncuyu Güncelle",
            ["AddPlayer_NickName"]    = "Takma Ad",
            ["AddPlayer_Name"]        = "İsim",
            ["AddPlayer_Avatar"]      = "Avatar",
            ["AddPlayer_Team"]        = "Takım (opsiyonel)",
            ["AddPlayer_ShortcutNumber"] = "Kısayol No",
            ["AddPlayer_ShortcutNumberInvalid"] = "0'dan büyük bir tam sayı girin.",
            ["AddPlayer_ShortcutNumberTaken"] = "Bu kısayol numarası {0} tarafından kullanılıyor.",

            // Skorbord
            ["Scoreboard_Title"]       = "Skorbord",
            ["Scoreboard_Reset"]       = "Skorları Sıfırla",
            ["Scoreboard_Enter"]       = "Onayla",
            ["Scoreboard_MatchTarget"] = "Hedef",
            ["Scoreboard_StartNewGame"]= "Yeni Oyun Başlat",
            ["Scoreboard_EndGame"]     = "Oyunu Bitir",
            ["Scoreboard_WarmUp"]      = "Isınma",
            ["Scoreboard_WarmUpTitle"] = "Isınma süresi",
            ["Scoreboard_MinutesFormat"] = "{0} dk",
            ["Scoreboard_Reconnect"]   = "Yeniden Bağlan",
            ["Scoreboard_PickPlayer"] = "Oyuncu Seç",
            ["Scoreboard_NoPlayers"]  = "Henüz oyuncu yok. Önce ekleyin.",
            ["Rank_Title"]              = "Sıralama",
            ["Rank_Players"]            = "Oyuncu",
            ["Rank_Period"]             = "Dönem",
            ["Rank_Period30"]           = "Son 30 gün",
            ["Rank_Period90"]           = "Son 90 gün",
            ["Rank_Period6m"]           = "Son 6 ay",
            ["Rank_PeriodYear"]         = "Bu yıl",
            ["Rank_PeriodAll"]          = "Tüm zamanlar",
            ["Rank_Sort"]               = "Sıralama ölçütü",
            ["Rank_SortAverage"]        = "Ortalama",
            ["Rank_SortWins"]           = "Galibiyet",
            ["Rank_SortHighRun"]        = "En yüksek seri",
            ["Rank_SortMatches"]        = "Maç",
            ["Rank_SortWinPercent"]     = "Galibiyet %",
            ["Rank_Empty"]              = "Bu dönemde maç yok.",
            ["Manage_EditPlayer"]       = "Oyuncuyu düzenle",
            ["Manage_FirstName"]        = "Ad",
            ["Manage_LastName"]         = "Soyad",
            ["Manage_Title"]            = "Yönetim",
            ["Manage_Tables"]           = "Masalar",
            ["Manage_Players"]          = "Oyuncular",
            ["Manage_Teams"]            = "Takımlar",
            ["Manage_Empty"]            = "Gösterilecek kayıt yok.",
            ["Manage_Table"]            = "Masa",
            ["Manage_ScoreboardNo"]     = "Skorboard",
            ["Manage_NoScoreboard"]     = "Skorboard atanmamış",
            ["Manage_Available"]        = "Boş",
            ["Manage_InUse"]            = "Kullanımda",
            ["Manage_Reserved"]         = "Rezerve",
            ["Manage_Maintenance"]      = "Bakımda",
            ["Manage_OutOfService"]     = "Hizmet dışı",
            ["Admin_Teams"]             = "Takımlar",
            ["Admin_TeamName"]          = "Takım adı",
            ["Admin_AddTeam"]           = "Takım Ekle",
            ["Admin_TeamsEmpty"]        = "Henüz takım yok. Yukarıdan ekleyin.",
            ["Admin_Players"]           = "Oyuncular",
            ["Admin_AddPlayer"]         = "Oyuncu Ekle",
            ["Admin_PlayersEmpty"]      = "Henüz oyuncu yok. Yukarıdan ekleyin.",
            ["Admin_DeletePlayer"]        = "Oyuncuyu Sil",
            ["Admin_DeletePlayerConfirm"] = "{0} kalıcı olarak silinsin mi? Bu işlem geri alınamaz.",
            ["Admin_DefaultPlayerDeleteBlocked"] = "Bu, Skorbord sayfası tarafından kullanılan varsayılan bir oyuncudur ve silinemez.",
            ["Admin_DeleteTeam"]          = "Takımı Sil",
            ["Admin_DeleteTeamConfirm"]   = "{0} kalıcı olarak silinsin mi? Bu işlem geri alınamaz.",

            // Oyuncu maç istatistikleri
            ["PlayerStats_Title"]         = "Oyuncu İstatistikleri",
            ["PlayerStats_Empty"]         = "Henüz maç sonucu yok.",
            ["PlayerStats_Wins"]          = "Galibiyet",
            ["PlayerStats_Losses"]        = "Mağlubiyet",
            ["PlayerStats_AvgInnings"]    = "Ort. El",
            ["PlayerStats_InningsChart"]  = "Maça Göre El Sayısı",
            ["PlayerStats_ScoringPace"]   = "Skor Temposu (Son Maç)",
            ["PlayerStats_Started"]       = "Başlangıç: {0:g}",
            ["PlayerStats_Ended"]         = "Bitiş: {0:g}",

            // SSH konsolu
            ["Ssh_Title"]           = "SSH Konsolu",
            ["Ssh_Host"]            = "Sunucu",
            ["Ssh_Port"]            = "Port",
            ["Ssh_Username"]        = "Kullanıcı Adı",
            ["Ssh_Password"]        = "Parola",
            ["Ssh_SaveCredentials"] = "Bilgileri Kaydet",
            ["Ssh_Command"]         = "Komut",
            ["Ssh_Run"]             = "Çalıştır",
            ["Ssh_Output"]          = "Çıktı",
            ["PlayerStats_MatchHistory"]  = "Maç Geçmişi",
            ["PlayerStats_Opponent"]      = "Rakip",
            ["PlayerStats_Win"]           = "G",
            ["PlayerStats_Loss"]          = "M",
        }
    };
    public string CurrentLanguage => _language;
    public string this[string key]
    {
        get
        {
            if (_translations.TryGetValue(_language, out var dict) && dict.TryGetValue(key, out var val))
                return val;
            if (_translations["en"].TryGetValue(key, out var fallback))
                return fallback;
            return key;
        }
    }

    public void SetLanguage(string language)
    {
        if (_language == language) return;
        _language = language;
        Preferences.Default.Set("app_language", language);
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    private LocalizationManager() { }
}
